--CREATE DATABASE users;

CREATE TABLE cards (
	card_id SERIAL PRIMARY KEY,
	card_name VARCHAR(50) NOT NULL,
	mana_cost INTEGER NOT NULL,
	description VARCHAR(150),
	rarity VARCHAR(15) NOT NULL,
	card_type VARCHAR(15) NOT NULL,
	class_type VARCHAR(15) NOT NULL
);

CREATE TABLE minions(
	card_id INTEGER REFERENCES cards(card_id) PRIMARY KEY,
	attack INTEGER NOT NULL,
	health INTEGER NOT NULL
);

CREATE TABLE weapons(
	card_id INTEGER REFERENCES cards(card_id) PRIMARY KEY,
	wepAttack INTEGER NOT NULL,
	charges INTEGER NOT NULL
);

DROP TABLE IF EXISTS weapons CASCADE;

INSERT INTO cards (card_name, mana_cost, description, rarity, card_type, class_type)
	VALUES('Abomination', 5, 'Taunt. Deathrattle: deal 2 damage to all characters.', 'rare', 'minion', 'neutral'),
	('Abusive Sergeant', 1, 'Battlecry: Give a minion +2 Attack this turn.', 'common', 'minion', 'neutral'),
	('Acolyte of Pain', 3, 'Whenever this minion tkaes damage, draw a card.', 'common', 'minion', 'neutral'),
	('Adrenaline Rush', 1, 'Draw a card. Combo: Draw 2 cards instead.', 'epic', 'spell', 'neutral'),
	('Al''Alkir the Windlord', 8, 'Windfury, Charge, Divine Shield, Taunt.', 'legendary', 'minion', 'shaman'),
	('Alarm-o-Bot', 3, 'At the start of your turn, swap tis minion with a random one in your hand.', 'rare', 'minion', 'neutral'),
	('Aldor Peacekeeper', 3, 'Battlecry: Change an enemy minion''s attack to 1.', 'rare', 'minion', 'paladin'),
	('Alexstrasza', 9, 'Battlecry: Set a hero''s remaining health to 15.', 'legendary', 'minion', 'neutral'),
	('Amani Berserker', 2, 'Enrage: +3 Attack.', 'common', 'minion', 'neutral'),
	('Ancestral Spirit', 2, 'Choose a minion. When that minion is destroyed, return it to the battlefield.', 'rare', 'spell', 'shaman'),
	('Ancient Brewmaster', 4, 'Battlecry: Return a friendly minion from the battlefield to your hand.', 'common', 'minion', 'neutral'),
	('Ancient Mage', 4, 'Battlecry: Give adjacent minions Spell Damage + 1.', 'rare', 'minion', 'neutral'),
	('Ancient of Lore', 7, 'Choose One - Draw 2 cards; or Restore 5 Health.', 'epic', 'minion', 'druid'),
	('Ancient of War', 7, 'Choose One - Taunt and +5 Health; or +5 Attack.', 'epic', 'minion', 'druid'),
	('Ancient Secrets', 0, 'Restore 5 Health.', 'common', 'spell', 'druid'),
	('Ancient Teachings', 0, 'Draw 2 cards.', 'common', 'spell', 'druid'),
	('Ancient Watcher', 2, 'Can''t Attack.', 'rare', 'minion', 'neutral'),
	('Angry Chicken', 1, 'Enrage +5 Attack.', 'rare', 'minion', 'neutral'),
	('Arathi Weaponsmith', 4, 'Battlecry: Equip a 2/2 weapon.', 'common', 'minion', 'warrior'),
	('Arcane Golem', 3, 'Charge. Battlecry: Give your opponent a Mana Crystal.', 'rare', 'minion', 'neutral'),
	('Archmage Antonidas', 7, 'Whenever you cast a spell, put a ''Fireball'' spell into your hand.', 'legendary', 'minion', 'mage'),
	('Argent Commander', 6, 'Charge, Divine Shield.', 'rare', 'minion', 'neutral'),
	('Argent Protector', 2, 'Battlecry: Give a friendly minion Divine Shield.', 'common', 'minion', 'paladin'),
	('Argent Squire', 1, 'Divine Shield.', 'common', 'minion', 'neutral'),
	('Armorsmith', 2, 'Whenever a friendly minion takes damage, gain 1 Armor.', 'rare', 'minion', 'warrior'),
	('Ashbringer', 5, '', 'legendary', 'weapon', 'paladin'),
	('Auchenai Soulpriest', 4, 'Your cards and powers that restore Health now deal damage instead.', 'rare', 'minion', 'priest'),
	('Avenging Wrath', 6, 'Deal 8 damage randomly split among enemy characters.', 'epic', 'spell', 'paladin'),
	('Azure Drake', 5, 'Spell Damage +1. Battlecry: Draw a card.', 'rare', 'minion', 'neutral'),
	('Baine Bloodhoof', 4, '', 'legendary', 'minion', 'neutral'),
	('Bane of Doom', 5, 'Deal 2 damage to a character. If that kills it, summon a random Demon.', 'epic', 'spell', 'warlock'),
	('Baron Geddon', 7, 'At the end of your turn, deal 2 damage to ALL other characters.', 'legendary', 'minion', 'neutral'),
	('Battle Rage', 2, 'Draw a card for each damaged friendly character.', 'common', 'spell', 'warrior'),
	('Bear Form', 0, '+2 Health and Taunt.', 'common', 'spell', 'druid'),
	('Bestial Wrath', 1, 'Give a Beast +2 Attack and Immune this turn.', 'epic', 'spell', 'hunter'),
	('Betrayal', 2, 'An enemy minion deals its damage to the minions next to it.', 'common', 'spell', 'rogue'),
	('Big Game Hunter', 3, 'Battlecry: Destroy a minion with an Attack of 7 or more.', 'epic', 'minion', 'neutral'),
	('Bite', 4, 'Give your hero +4 Attack this turn and 4 Armor.', 'rare', 'spell', 'druid'),
	('Blade Flurry', 2, 'Destroy your weapon and deal its damage to all enemies.', 'rare', 'spell', 'rogue'),
	('Blessed Champion', 5, 'Double a minion''s Attack.', 'rare', 'spell', 'paladin'),
	('Blessing of Wisdom', 1, 'Choose a minion. Whenever it attacks, draw a card.', 'common', 'spell', 'paladin'),
	('Blizzard', 6, 'Deal 2 damage to all enemy minions and Freeze them.', 'rare', 'spell', 'mage'),
	('Blood Fury', 3, '', 'common', 'weapon', 'warlock'),
	('Blood Imp', 1, 'Stealth. At the end of your turn, give another random friendly minion +1 Health.', 'common', 'minion', 'warlock'),
	('Blood Knight', 3, 'Battlecry: All minions lose Divine Shield. Gain +3/+3 for each Shield lost.', 'epic', 'minion', 'neutral'),
	('Bloodmage Thalnos', 2, 'Spell Damage +1. Deathrattle: Draw a card.', 'legendary', 'minion', 'neutral'),
	('Bloodsail Corsair', 1, 'Battlecry: Remove 1 Durability from your opponent''s weapon.', 'rare', 'minion', 'neutral'),
	('Bloodsail Raider', 2, 'Battlecry: Gain Attack equal to the Attack of your weapon.', 'common', 'minion', 'neutral'),
	('Boar', 1, '', 'common', 'minion', 'neutral'),
	('Brawl', 5, 'Destroy all minions except one.(chosen randomly)', 'epic', 'spell', 'warrior'),
	('Brewmaster', 4, '', 'common', 'minion', 'neutral'),
	('Cabal Shadow Priest', 6, 'Battlecry: Take control of an enemy minion that has 2 or less Attack.', 'epic', 'minion', 'priest'),
	('Cairne Bloodhoof', 6, 'Deathrattle: Summon a 4/5 Baine Bloodhoof.', 'legendary', 'minion', 'neutral'),
	('Captain Greenskin', 5, 'Battlecry: Give your weapon +1/+1.', 'legendary', 'minion', 'neutral'),
	('Cenarius', 9, '+2/+2; or Summon two 2/2 Treants with Taunt.', 'legendary', 'minion', 'druid'),
	('Chaos Bolt', 2, 'Deal 2 damage to a minion. If the target is a Demon, give it +2/+2 instead.', 'common', 'spell', 'warlock'),
	('Circle of Healing', 0, 'Restore 4 Health to ALL minions.', 'common', 'spell', 'priest'),
	('Cold Blood', 1, 'Give a minion +2 Attack. Combo: +4 Attack instead.', 'common', 'spell', 'rogue'),
	('Coldlight Oracle', 3, 'Battlecry: Each player draws 2 cards.', 'rare', 'minion', 'neutral'),
	('Coldlight Seer', 3, 'Battlecry: Give ALL other Murlocs +2 Health.', 'rare', 'minion', 'neutral'),
	('Commanding Shout', 2, 'Your minions can''t be reduced below 1 Health this turn.', 'rare', 'spell', 'warrior'),
	('Conceal', 1, 'Give your minions Stealth until your next turn.', 'common', 'spell', 'rogue'),
	('Cone of Cold', 4, 'Freeze a minion and the minions next to it, and deal 1 damage to them.', 'common', 'spell', 'mage'),
	('Counterspell', 3, 'Secret: When your opponent casts a spell, Counter it.', 'rare', 'spell', 'mage'),
	('Crazed Alchemist', 2, 'Battlecry: Swap the Attack and Health of a minion.', 'rare', 'minion', 'neutral'),
	('Crazy Monkey', 1, 'Battlecry: Throw Bananas.', 'common', 'minion', 'neutral'),
	('Cruel Taskmaster', 2, 'Battlecry: Deal 1 damage to a minion and give it +2 Attack.', 'common', 'minion', 'warrior'),
	('Cult Master', 4, 'Whenever one of your other minions dies, draw a card.', 'common', 'minion', 'neutral'),
	('Dark Iron Dwarf', 4, 'Battlecry: Give a minion +2 Attack this turn.', 'common', 'minion', 'neutral'),
	('Deadly Shot', 3, 'Destroy a random enemy minion.', 'common', 'spell', 'hunter'),
	('Deathwing', 10, 'Battlecry: Destroy all other minions and discard your hand.', 'legendary', 'minion', 'neutral'),
	('Defender of Argus', 4, 'Battlecry: Give adjacent minions +1/+1 and Taunt.', 'rare', 'minion', 'neutral'),
	('Defias Ringleader', 2, 'Combo: Summon a 2/1 Defias Bandit.', 'common', 'minion', 'rogue'),
	('Demolisher', 3, 'At the start of your turn, deal 2 damage to a random enemy.', 'rare', 'minion', 'neutral'),
	('Demonfire', 2, 'Deal 2 damage to a minion. If it''s a friendly Demon give it +2/+2 instead.', 'common', 'spell', 'warlock'),
	('Devilsaur', 5, '', 'common', 'minion', 'neutral'),
	('Dire Wolf Alpha', 2, 'Adjacent minions have +1 Attack.', 'common', 'minion', 'neutral'),
	('Dispel', 0, 'Silence a minion.', 'common', 'spell', 'druid'),
	('Divine Favor', 3, 'Draw cards until you have as many in hand as your opponent.', 'rare', 'spell', 'paladin'),
	('Doomguard', 5, 'Charge. Battlecry: Discard two random cards.', 'rare', 'minion', 'warlock'),
	('Doomhammer', 5, 'Windfury, Overload: 2.', 'epic', 'weapon', 'shaman'),
	('Doomsayer', 2, 'At the start of your turn, destroy ALL minions.', 'epic', 'minion', 'neutral'),
	('Dread Corsair', 4, 'Taunt. Costs (1) less per Attack of your weapon.', 'common', 'minion', 'neutral'),
	('Druid of the Claw', 5, 'Choose One - Charge; or +2 Health and Taunt.', 'common', 'minion', 'druid'),
	('Dust Devil', 1, 'Windfury. Overload: (2).', 'common', 'minion', 'shaman'),
	('Eaglehorn Bow', 3, 'Whenever a Secret is revealed, gain +1 Durability.', 'rare', 'weapon', 'hunter'),
	('Earth Elemental', 5, 'Taunt. Overload: (3).', 'epic', 'minion', 'shaman'),
	('Earth Shock', 1, 'Silence a minion, then deal 1 damage to it.', 'common', 'spell', 'neutral'),
	('Earthen Ring Farseer', 3, 'Battlecry: Restore 3 Health.', 'common', 'minion', 'neutral'),
	('Edwin Vancleef', 3, 'Combo: Gain +2/+2 for each card played earlier this turn.', 'legendary', 'minion', 'rogue'),
	('Emboldener 3000', 1, 'At the end of your turn, give a random minion +1/+1.', 'common', 'minion', 'neutral'),
	('Emperor Cobra', 3, 'Destroy any minion damaged by this minion.', 'rare', 'minion', 'neutral'),
	('Equality', 2, 'Change the Health of ALL minions to 1.', 'rare', 'spell', 'paladin'),
	('Ethereal Arcanist', 4, 'If you control a Secret at the end of your turn, gain +2/+2.', 'rare', 'minion', 'mage'),
	('Eviscerate', 2, 'Deal 2 damage. Combo: Deal 4 damage instead.', 'common', 'spell', 'rogue'),
	('Explosive Shot', 5, 'Deal 5 damage to a minion and 2 damage to adjacent ones.', 'rare', 'spell', 'hunter'),
	('Explosive Trap', 2, 'Secret: When your hero is attacked, deal 2 damage to all enemies.', 'common', 'spell', 'hunter'),
	('Eye for an Eye', 1, 'Secret: When your hero takes damage, deal that much damage to the enemy hero.', 'common', 'spell', 'paladin'),
	('Faceless Manipulator', 5, 'Battlecry: Choose a minion and become a copy of it.', 'epic', 'minion', 'neutral'),
	('Faerie Dragon', 2, 'Can''t be targeted by Spells or Hero Powers.', 'common', 'minion', 'neutral'),
	('Far Sight', 3, 'Draw a card. That card costs (3) less.', 'epic', 'spell', 'shaman'),
	('Felguard', 3, 'Taunt. Battlecry: Destroy one of your Mana Crystals.', 'rare', 'minion', 'warlock'),
	('Fen Creeper', 5, 'Taunt.', 'common', 'minion', 'neutral'),
	('Feral Spirit', 3, 'Summon two 2/3 Spirit Wolves with Taunt. Overload: (2)', 'rare', 'spell', 'shaman'),
	('Flame Burst', 3, 'Shoot 5 missiles at random enemies for 1 damage each.', 'common', 'spell', 'neutral'),
	('Flame Imp', 1, 'Battlecry: Deal 3 damage to your hero.', 'common', 'minion', 'warlock'),
	('Flare', 1, 'All minions lose Stealth. Destroy all enemy Secrets. Draw a card.', 'rare', 'spell', 'hunter'),
	('Flesheating Ghoul', 3, 'Whenever a minion dies, gain +1 Attack.', 'common', 'minion', 'neutral'),
	('Force of Nature', 6, 'Summon three 2/2 Treants with Charge that die at the end of the turn.', 'epic', 'spell', 'druid'),
	('Forked Lightning', 1, 'Deal 2 damage to 2 random enemy minions. Overload: (2).', 'common', 'spell', 'shaman'),
	('Freezing Trap', 2, 'Secret: When an enemy minion attacks, return it to its owner''s hand and it costs (2) more.', 'common', 'spell', 'hunter'),
	('Frog', 0, 'Taunt.', 'common', 'minion', 'neutral'),
	('Frost Elemental', 6, 'Battlecry: Freeze a character.', 'common', 'minion', 'neutral'),
	('Frothing Berserker', 3, 'Whenever a minion takes damage, gain +1 Attack.', 'rare', 'minion', 'warrior'),
	('Gadgetzan Auctioneer', 6, 'Whenever you cast a spell, draw a card.', 'rare', 'minion', 'neutral'),
	('Gladiator''s Longbow', 7, 'Your hero is Immune while attacking.', 'epic', 'weapon', 'hunter'),
	('Gorehowl', 7, 'Attacking a minion costs 1 Attack instead of 1 Durability.', 'epic', 'weapon', 'warrior'),
	('Greater Heal', 2, 'Restore 2 Health to a character for each card in your opponent''s hand.', 'rare', 'spell', 'priest'),
	('Grommash Hellscream', 8, 'Charge. Enrage: +6 Attack.', 'legendary', 'minion', 'warrior'),
	('Gruul', 8, 'At the end of each turn, gain +1/+1.', 'legendary', 'minion', 'neutral'),
	('Harrison Jones', 5, 'Battlecry: Destroy your opponent weapon and draw cards equal to its durability.', 'legendary', 'minion', 'neutral'),
	('Harvest Golem', 3, 'Deathrattle: Summon a 2/1 Damaged Golem.', 'common', 'minion', 'neutral'),
	('Headcrack', 3, 'Deal 2 damage to the enemy hero. Combo: Return this card to your hand next turn.', 'rare', 'spell', 'rogue'),
	('Hogger', 6, 'At the end of your turn, Summon a 2/2 Gnoll with Taunt.', 'legendary', 'minion', 'neutral'),
	('Holy Fire', 6, 'Deal 5 damage. Restore 5 Health to your hero.', 'rare', 'spell', 'priest'),
	('Holy Wrath', 5, 'Draw a card and deal damage equal to its cost.', 'rare', 'spell', 'paladin'),
	('Homing Chicken', 1, 'At the start of your turn, destroy this minion and draw 3 cards.', 'common', 'minion', 'neutral'),
	('Hungry Crab', 1, 'Battlecry: Destroy a Murloc and gain +2/+2.', 'epic', 'minion', 'neutral'),
	('Ice Barrier', 3, 'Secret: As soon as your hero is attacked, gain 8 Armor.', 'common', 'spell', 'mage'),
	('Ice Block', 3, 'Secret: When your hero takes fatal damage, prevent it and become Immune this turn.', 'epic', 'spell', 'mage'),
	('Ice Lance', 1, 'Freeze a character. If it was already Frozen, deal 4 damage instead.', 'common', 'spell', 'mage'),
	('Illidan Stormrage', 6, 'Whenever you play a card, summon a 2/1 Flame of Azzinoth.', 'legendary', 'minion', 'neutral'),
	('Imp Master', 3, 'At the end of your turn, deal 1 damage to this minion and Summon a 1/1 Imp.', 'rare', 'minion', 'neutral'),
	('Injured Blademaster', 3, 'Battlecry: Deal 4 damage to HIMSELF.', 'rare', 'minion', 'neutral'),
	('Inner Fire', 1, 'Change a minions Attack to be equal to its Health.', 'common', 'spell', 'priest'),
	('Inner Rage', 0, 'Deal 1 damge to a minion and give it +2 Attack.', 'common', 'spell', 'warrior'),
	('Ironbeak Owl', 2, 'Battlecry: Silence a minion.', 'common', 'minion', 'neutral'),
	('Jungle Panther', 3, 'Stealth.', 'common', 'minion', 'neutral'),
	('Keeper of the Grove', 4, 'Choose One - Deal 2 damage; or Silence a minion.', 'rare', 'minion', 'druid'),
	('Kidnapper', 6, 'Combo: Return a minion to its owner''s hand.', 'epic', 'minion', 'rogue'),
	('King Krush', 9, 'Charge.', 'legendary', 'minion', 'hunter'),
	('King Mukla', 3, 'Battlecry: Give your opponent 2 Bananas.', 'legendary', 'minion', 'neutral'),
	('Kirin Tor Mage', 3, 'Battlecry: The next Secret you play this turn costs (0).', 'rare', 'minion', 'mage'),
	('Knife Juggler', 2, 'After you summon a minion, deal 1 damage to a random enemy.', 'rare', 'minion', 'neutral'),
	('Laughing Sister', 3, 'Can''t be targeted by Spells or Hero powers.', 'common', 'minion', 'neutral'),
	('Lava Burst', 3, 'Deal 5 damage. Overload: (2)', 'rare', 'spell', 'shaman'),
	('Lay on Hands', 8, 'Restore 8 Health. Draw 3 cards.', 'epic', 'spell', 'paladin'),
	('Leeroy Jenkins', 5, 'Charge. Battlecry: Summon two 1/1 Whelps for your opponent.', 'legendary', 'minion', 'neutral'),
	('Legacy of the Emperor', 3, 'Give your minions +2/+2.', 'common', 'spell', 'neutral'),
	('Leokk', 3, 'Other friendly minions have +1 Attack.', 'common', 'minion', 'hunter'),
	('Leper Gnome', 1, 'Deathrattle: Deal 2 damage to the enemy hero.', 'common', 'minion', 'neutral'),
	('Lightning Bolt', 1, 'Deal 3 damage. Overload: (1)', 'common', 'spell', 'shaman'),
	('Lightning Storm', 3, 'Deal 2-3 damage to all enemy minions. Overload: (2)', 'rare', 'spell', 'shaman'),
	('Lightspawn', 4, 'This minion''s Attack is always equal to its Health.', 'common', 'minion', 'priest'),
	('Lightwarden', 1, 'Whenever a character is healed, gain +2 Attack.', 'rare', 'minion', 'neutral'),
	('Lightwell', 2, 'At the start of your turn, restore 3 Health to a damaged friendly character.', 'rare', 'minion', 'priest'),
	('Loot Hoarder', 2, 'Deathrattle: Draw a card.', 'common', 'minion', 'neutral'),
	('Lord Jaraxxus', 9, 'Battlecry: Destroy your hero and replace him with Lord Jaraxxus.', 'legendary', 'minion', 'warlock'),
	('Lorewalker Cho', 2, 'Whenever a player casts a spell, put a copy into the other player''s hand.', 'legendary', 'minion', 'neutral'),
	('Mad Bomber', 2, 'Battlecry: Deal 3 damage randomly split between all other characters.', 'common', 'minion', 'neutral'),
	('Malygos', 9, 'Spell Damage +5.', 'legendary', 'minion', 'neutral'),
	('Mana Addict', 2, 'Whenever you cast a spell, gain +2 Attack this turn.', 'rare', 'minion', 'neutral'),
	('Mana Tide Totem', 3, 'At the end of your turn, draw a card.', 'rare', 'minion', 'shaman'),
	('Mana Wyrm', 1, 'Whenever you cast a spell, gain +1 Attack.', 'rare', 'minion', 'mage'),
	('Mark of Nature', 3, 'Choose One - Give a minion +4 Attack; or +4 Health and Taunt.', 'common', 'spell', 'druid'),
	('Mass Dispel', 4, 'Silence all enemy minions. Draw a card.', 'rare', 'spell', 'priest'),
	('Master of Disguise', 4, 'Battlecry: Give a friendly minion Stealth.', 'rare', 'minion', 'rogue'),
	('Master Swordsmith', 2, 'At the end of your turn, give another random friendly minion +1 Attack.', 'rare', 'minion', 'neutral'),
	('Mind Control Tech', 3, 'Battlecry: If your opponent has 4 or more minions, take control of one at random.', 'rare', 'minion', 'neutral'),
	('Mindgames', 4, 'Put a copy of a random minion from your opponent''s deck into the battlefield.', 'epic', 'spell', 'priest'),
	('Mirror Entity', 3, 'Secret: When your opponent plays a minion, summon a copy of it.', 'common', 'spell', 'mage'),
	('Mogu''shan Warden', 4, 'Taunt.', 'common', 'minion', 'neutral'),
	('Molten Giant', 20, 'Costs (1) less for each damage your hero has taken.', 'epic', 'minion', 'neutral'),
	('Mortal Strike', 4, 'Deal 4 damage. If your hero has 12 or less Health, deal 6 damage instead.', 'rare', 'spell', 'warrior'),
	('Mountain Giant', 12, 'Costs (1) less for each other card in your hand.', 'epic', 'minion', 'neutral'),
	('Murloc Tidecaller', 1, 'Whenever a Murloc is summoned, gain +1 Attack.', 'rare', 'minion', 'neutral'),
	('Murloc Warleader', 3, 'All other Murlocs have +2/+1.', 'epic', 'minion', 'neutral'),
	('Nat Pagle', 2, 'At the end of your turn, you have a 50% chance to draw a card.', 'legendary', 'minion', 'neutral'),
	('Naturalize', 1, 'Destroy a minion. Your opponent draws 2 cards.', 'common', 'spell', 'druid'),
	('Noble Sacrifice', 1, 'Secret: Whenever an enemy attacks, summon a 2/1 Defender as the new target.', 'common', 'spell', 'paladin'),
	('Nourish', 5, 'Choose One - Gain 2 Mana Crystals; or Draw 3 cards.', 'rare', 'spell', 'druid'),
	('Nozdormu', 9, 'Players only have 15 seconds to take their turns.', 'legendary', 'minion', 'neutral'),
	('Onyxia', 9, 'Battlecry: Summon 1/1 Whelps until your side of the battlefield is full.', 'legendary', 'minion', 'neutral'),
	('Patient Assassin', 2, 'Stealth. Destroy any minion damaged by this minion.', 'epic', 'minion', 'rogue'),
	('Penance', 3, 'Deal 3 damage. Restore 3 Health to your hero.', 'common', 'spell', 'priest'),
	('Perdition''s Blade', 3, 'Battlecry: Deal 1 damage. Combo: Deal 2 damage instead.', 'rare', 'weapon', 'rogue'),
	('Pint-Sized Summoner', 2, 'The first minion you play each turn costs (1) less.', 'rare', 'minion', 'neutral'),
	('Pit Lord', 4, 'Battlecry: Deal 5 damage to your hero.', 'epic', 'minion', 'warlock'),
	('Power of the Wild', 2, 'Choose one - Give your minions +1/+1; or Summon a 3/2 Panther.', 'common', 'spell', 'druid'),
	('Power Overwhelming', 1, 'Give a friendly minion +4/+4 until the end of the turn. Then, it dies. Horribly.', 'common', 'spell', 'warlock'),
	('Preparation', 0, 'The next spell you cast this turn costs (3) less.', 'epic', 'spell', 'rogue'),
	('Priestess of Elune', 6, 'Battlecry: Restore 4 Health to your hero.', 'common', 'minion', 'neutral'),
	('Prophet Velen', 7, 'Double the damage and healing of your spells and Hero Power.', 'legendary', 'minion', 'priest'),
	('Pyroblast', 10, 'Deal 10 damage.', 'epic', 'spell', 'mage'),
	('Questing Adventurer', 3, 'Whenever you play a card, gain +1/+1.', 'rare', 'minion', 'neutral'),
	('Raging Worgen', 3, 'Enrage: Windfury and +1 Attack.', 'common', 'minion', 'neutral'),
	('Ragnaros the Firelord', 8, 'Can''t Attack. At the end of your turn, deal 8 damage to a random enemy.', 'legendary', 'minion', 'neutral'),
	('Rampage', 2, 'Give a damaged minion +3/+3.', 'common', 'spell', 'warrior'),
	('Ravenholdt Assassin', 7, 'Stealth.', 'rare', 'minion', 'neutral'),
	('Redemption', 1, 'Secret: When one of your minions dies, return it to life with 1 Health.', 'common', 'spell', 'paladin'),
	('Repentance', 1, 'Secret: When your opponent plays a minion, reduce its Health to 1.', 'common', 'spell', 'paladin'),
	('Savagery', 1, 'Deal damage equal to your hero''s Attack to a minion.', 'rare', 'spell', 'druid'),
	('Savannah Highmane', 6, 'Deathrattle: Summon two 2/2 Hyenas.', 'rare', 'minion', 'hunter'),
	('Scarlet Crusader', 3, 'Divine Shield.', 'common', 'minion', 'neutral'),
	('Scavenging Hyena', 2, 'Whenever a friendly Beast dies, gain +2/+1.', 'common', 'minion', 'hunter'),
	('Sea Giant', 10, 'Costs (1) less for each other minion on the battlefield.', 'epic', 'minion', 'neutral'),
	('Secretkeeper', 1, 'Whenever a Secret is played, gain +1/+1.', 'rare', 'minion', 'neutral'),
	('Sense Demons', 3, 'Put 2 random Demons from your deck into your hand.', 'common', 'spell', 'warlock'),
	('Shadow Madness', 4, 'Gain control of an enemy minion with 3 or less Attack until the end of turn.', 'rare', 'spell', 'priest'),
	('Shadowflame', 4, 'Destroy a friendly minion and deal its Attack damage to all enemy minions.', 'rare', 'spell', 'warlock'),
	('Shadowform', 3, 'Your Hero Power becomes ''Deal 2 damage''. If already in Shadowform: 3 damage.', 'epic', 'spell', 'priest'),
	('Shadowstep', 0, 'Return a friendly minion to your hand. It costs (2) less.', 'common', 'spell', 'rogue'),
	('Shield Slam', 1, 'Deal 1 damage to a minion for each Armor you have.', 'epic', 'spell', 'warrior'),
	('Shieldbearer', 1, 'Taunt.', 'common', 'minion', 'neutral'),
	('SI:7 Agent', 3, 'Combo: Deal 2 damage.', 'rare', 'minion', 'rogue'),
	('Silence', 0, 'Silence a minion.', 'common', 'spell', 'priest'),
	('Silver Hand Knight', 5, 'Battlecry: Summon a 2/2 Squire.', 'common', 'minion', 'neutral'),
	('Siphon Soul', 6, 'Destroy a minion. Restore 3 Health to your hero.', 'rare', 'spell', 'warlock'),
	('Slam', 2, 'Deal 2 damage to a minion. If it survives, draw a card.', 'common', 'spell', 'warrior'),
	('Snake Trap', 2, 'Secret: When one of your minions is attacked, summon three 1/1 Snakes.', 'epic', 'spell', 'hunter'),
	('Snipe', 3, 'Secret: When your opponent plays a minion, deal 4 damage to it.', 'common', 'spell', 'hunter'),
	('Sorcerer''s Apprentice', 2, 'Your spells cost (1) less.', 'common', 'minion', 'mage'),
	('Soul of the Forest', 4, 'Give your minions "Deathrattle: Summon a 2/2 Treant.".', 'common', 'spell', 'druid'),
	('Spellbender', 3, 'Secret: When an enemy casts a spell on a minion, summon a 1/3 as the new target.', 'epic', 'spell', 'mage'),
	('Spellbreaker', 4, 'Battlecry: Silence a minion.', 'common', 'minion', 'neutral'),
	('Spiteful Smith', 5, 'Enrage: Your weapon has +2 attack.', 'common', 'minion', 'neutral'),
	('Sprint', 7, 'Draw 4 cards.', 'common', 'spell', 'rogue'),
	('Stampeding Kodo', 5, 'Battlecry: Destroy a random enemy minion with 2 or less Attack.', 'rare', 'minion', 'neutral'),
	('Starfall', 0, 'Deal 5 damage to a minion.', 'common', 'spell', 'druid'),
	('Stormwind Knight', 4, 'Charge.', 'common', 'minion', 'neutral'),
	('Stranglethorn Tiger', 5, 'Stealth.', 'common', 'minion', 'neutral'),
	('Sunfury Protector', 2, 'Battlecry: Give adjacent minions Taunt.', 'rare', 'minion', 'neutral'),
	('Sunwalker', 6, 'Taunt. Divine Shield.', 'rare', 'minion', 'neutral'),
	('Sword of Justice', 3, 'Whenever you summon a minion, give it +1/+1 and this loses 1 Durability.', 'epic', 'weapon', 'paladin'),
	('Sylvanas Windrunner', 6, 'Deathrattle: Take control of a random enemy minion.', 'legendary', 'minion', 'neutral'),
	('Tauren Warrior', 3, 'Taunt. Enrage: +3 Attack', 'common', 'minion', 'neutral'),
	('Temple Enforcer', 6, 'Battlecry: Give a friendly minion +3 Health.', 'common', 'minion', 'priest'),
	('Tirion Fordring', 8, 'Divine Shield. Taunt. Deathrattle: Equip a 5/3 Ashbringer.', 'legendary', 'minion', 'neutral'),
	('Truesilver Champion', 4, 'Whenever your hero attacks, restore 2 Health to it.', 'common', 'weapon', 'paladin'),
	('Twilight Drake', 4, 'Battlecry: Gain +1 Health for each card in your hand.', 'rare', 'minion', 'neutral'),
	('Twisting Nether', 8, 'Destroy all minions.', 'epic', 'spell', 'warlock'),
	('Unleash the Hounds', 3, 'For each enemy minion, summon a 1/1 Hound with Charge.', 'common', 'spell', 'hunter'),
	('Vaporize', 3, 'Secret: When a minion attacks your hero, destroy it.', 'rare', 'spell', 'mage'),
	('Violet Teacher', 4, 'Whenever you cast a spell, summon a 1/1 Violet Apprentice.', 'rare', 'minion', 'neutral'),
	('Ysera', 9, 'At the end of your turn draw a Dream Card.', 'legendary', 'minion', 'neutral');
	
	

INSERT INTO minions (card_id, attack, health)
	VALUES (1, 4, 4),
	(2,2,1),
	(3,1,3),
	(5,3,5),
	(6,0,3),
	(7,3,3),
	(8,8,8),
	(9,2,3),
	(11,5,4),
	(12,2,5),
	(13,5,5),
	(14,5,5),
	(17,4,5),
	(18,1,1),
	(19,3,3),
	(20,4,2),
	(21,5,7),
	(22,4,2),
	(23,2,2),
	(24,1,1),
	(25,1,4),
	(27,3,5),
	(29,4,4),
	(30,4,5),
	(32,7,5),
	(37,4,2),
	(44,0,1),
	(45,3,3),
	(46,1,1),
	(47,1,2),
	(48,2,3),
	(49,1,1),
	(51,4,4),
	(52,4,5),
	(53,4,5),
	(54,5,4),
	(55,5,8),
	(59,2,2),
	(60,2,3),
	(65,2,2),
	(66,1,2),
	(67,2,2),
	(68,4,2),
	(69,4,4),
	(71,12,12),
	(72,2,3),
	(73,2,2),
	(74,1,4),
	(76,5,5),
	(77,2,2),
	(80,5,7),
	(82,0,7),
	(83,3,3),
	(84,4,4),
	(85,1,3),
	(87,7,8),
	(89,3,3),
	(90,2,2),
	(91,0,4),
	(92,2,3),
	(94,3,3),
	(99,3,3),
	(100,3,2),
	(102,3,5),
	(103,3,6),
	(106,3,2),
	(108,2,3),
	(112,0,1),
	(113,5,5),
	(114,2,4),
	(115,4,4),
	(119,4,9),
	(120,7,7),
	(121,5,4),
	(122,2,3),
	(124,4,4),
	(127,0,1),
	(128,1,2),
	(132,7,5),
	(133,1,5),
	(134,4,7),
	(137,2,1),
	(138,4,2),
	(139,2,4),
	(140,5,3),
	(141,8,8),
	(142,5,5),
	(143,4,3),
	(144,3,2),
	(145,3,5),
	(148,6,2),
	(150,2,4),
	(151,2,1),
	(154,0,5),
	(155,1,2),
	(156,0,5),
	(157,2,1),
	(158,3,15),
	(159,0,4),
	(160,3,2),
	(161,4,12),
	(162,1,3),
	(163,0,3),
	(164,1,3),
	(167,4,4),
	(168,1,3),
	(169,3,3),
	(172,1,7),
	(173,8,8),
	(175,8,8),
	(176,1,2),
	(177,3,3),
	(178,0,4),
	(182,8,8),
	(183,8,8),
	(184,1,1),
	(187,2,2),
	(188,5,6),
	(192,5,4),
	(193,7,7),
	(195,2,2),
	(196,3,3),
	(197,8,8),
	(199,7,5),
	(203,6,5),
	(204,3,1),
	(205,2,2),
	(206,8,8),
	(207,1,2),
	(214,0,4),
	(215,3,3),
	(217,4,4),
	(222,3,2),
	(225,4,3),
	(226,4,6),
	(228,3,5),
	(230,2,5),
	(231,5,5),
	(232,2,3),
	(233,4,5),
	(235,5,5),
	(236,2,3),
	(237,6,6),
	(238,6,6),
	(244,3,5),
	(245,4,12);

INSERT INTO weapons (card_id, wepAttack, charges)
	VALUES (26,5,3),
	(43,3,8),
	(81,2,8),
	(86,3,2),
	(116,5,2),
	(117,7,1),
	(186,2,2),
	(234,1,5),
	(239,4,2);

SELECT c.card_id, c.card_name,
	c.mana_cost, c.description, c.rarity, c.card_type,
	c.class_type, m.attack, m.health, w.charges
FROM cards c 
	FULL JOIN minions m ON (c.card_id = m.card_id)
	FULL JOIN weapons w ON (c.card_id = w.card_id);
	--WHERE LOWER(c.card_name) = 'boar';

SELECT * FROM cards WHERE card_type = 'weapon';
	